### ISSUE TITLE
NomalForm

### ISSUE THREAD

**Issue by k-kawaa** [PJZ9n/FormExample#1]
クラスの最後の}がありません..
NomalForm 77行目です....

**Comment by PJZ9n** [comment]
報告ありがとうございます。
[こちらのサイト](http://samplecode.xyz/?page=codechecker)で構文チェックを行ったところ、エラーは検出されませんとのことでした。
![screenshot_20200622_181238](https://user-images.githubusercontent.com/38120936/85270369-279dfe00-b4b4-11ea-9188-60c3d4765a1e.png)
